name: Deploy to production

on:
 push:
 branches: [main]

jobs:
 deploy:
 runs-on: ubuntu-latest
 steps:
 - uses: actions/checkout@v4
 - run: npm ci
 - run: npm run build
 - name: Install Octopus CLI
 uses: OctopusDeploy/install-octopus-cli-action@v4.1.0
 - run: npm run deploy
